// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzP8Z13Z0Pg3b5grTVNSL-Q-h5o3DbDo',
    appId: '1:729007544286:web:3bde1bea992131801a6f4f',
    messagingSenderId: '729007544286',
    projectId: 'h-bionic',
    authDomain: 'h-bionic.firebaseapp.com',
    storageBucket: 'h-bionic.appspot.com',
    measurementId: 'G-WTBX5LJHFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCftfg5mdjqNd40uL9ya2RZdOwqt1m4r2s',
    appId: '1:729007544286:android:2d62f61ebe5c45361a6f4f',
    messagingSenderId: '729007544286',
    projectId: 'h-bionic',
    storageBucket: 'h-bionic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWgzBJO-LhjGZt_EAuw5I1_RvXAc5aDk',
    appId: '1:729007544286:ios:4fa40ff0b4b98e091a6f4f',
    messagingSenderId: '729007544286',
    projectId: 'h-bionic',
    storageBucket: 'h-bionic.appspot.com',
    iosBundleId: 'com.example.hBionic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWgzBJO-LhjGZt_EAuw5I1_RvXAc5aDk',
    appId: '1:729007544286:ios:bf634ef7a1c7398e1a6f4f',
    messagingSenderId: '729007544286',
    projectId: 'h-bionic',
    storageBucket: 'h-bionic.appspot.com',
    iosBundleId: 'com.example.hBionic.RunnerTests',
  );
}
